# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf7\x01\n\x10UserInfoResponce\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0c\n\x04slug\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x12\n\nis_blogger\x18\x07 \x01(\x08\x12&\n\x05image\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x30\n\x0fsocial_networks\x18\t \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x10\n\x08position\x18\n \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x14GetUserBySlugRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\"7\n\x11\x43heckTokenRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\")\n\x12\x43heckTokenResponce\x12\x13\n\x0bpermissions\x18\x01 \x03(\t\"/\n\x0fGetUsersRequest\x12\x0e\n\x06search\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\"L\n\x13GetUserListResponce\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.UserInfoResponce\x12\x13\n\x0btotal_users\x18\x02 \x01(\x05\"F\n\x15GetUserByFilterRequst\x12\x0e\n\x06search\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0f\n\x07role_id\x18\x03 \x01(\t2\xba\x02\n\x05Users\x12\x38\n\x0cGetUsersById\x12\x13.GetUserByIdRequest\x1a\x11.UserInfoResponce\"\x00\x12<\n\x0eGetUsersBySlug\x12\x15.GetUserBySlugRequest\x1a\x11.UserInfoResponce\"\x00\x12;\n\x0ePostCheckToken\x12\x12.CheckTokenRequest\x1a\x13.CheckTokenResponce\"\x00\x12\x37\n\x0bGetUserList\x12\x10.GetUsersRequest\x1a\x14.GetUserListResponce\"\x00\x12\x43\n\x11GetUserListByRole\x12\x16.GetUserByFilterRequst\x1a\x14.GetUserListResponce\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERINFORESPONCE']._serialized_start=45
  _globals['_USERINFORESPONCE']._serialized_end=292
  _globals['_GETUSERBYIDREQUEST']._serialized_start=294
  _globals['_GETUSERBYIDREQUEST']._serialized_end=326
  _globals['_GETUSERBYSLUGREQUEST']._serialized_start=328
  _globals['_GETUSERBYSLUGREQUEST']._serialized_end=364
  _globals['_CHECKTOKENREQUEST']._serialized_start=366
  _globals['_CHECKTOKENREQUEST']._serialized_end=421
  _globals['_CHECKTOKENRESPONCE']._serialized_start=423
  _globals['_CHECKTOKENRESPONCE']._serialized_end=464
  _globals['_GETUSERSREQUEST']._serialized_start=466
  _globals['_GETUSERSREQUEST']._serialized_end=513
  _globals['_GETUSERLISTRESPONCE']._serialized_start=515
  _globals['_GETUSERLISTRESPONCE']._serialized_end=591
  _globals['_GETUSERBYFILTERREQUST']._serialized_start=593
  _globals['_GETUSERBYFILTERREQUST']._serialized_end=663
  _globals['_USERS']._serialized_start=666
  _globals['_USERS']._serialized_end=980
# @@protoc_insertion_point(module_scope)
